#!/usr/bin/env python3
"""
generate_mac_pblocks.py
-----------------------

Emit a Vivado XDC fragment that pins each MAC engine of the 1M-tap FIR
in the BFDAC project (xc7a200tfbg484-3, Artix-7 200T) to a local PBLOCK
containing exactly one DSP48E1 site and a small adjacent SLICE box.

This keeps the 16-bit CARRY4 fabric overflow logic in
``polyphase_mac_engine.sv`` glued to its DSP and protects the 2.8 ns
setup budget at 357.46 MHz.

DSP placement wraps across multiple DSP columns once a column fills up,
controlled by ``DSPS_PER_COLUMN``. SLICE bounding boxes shift right by
``SLICE_COLUMNS_PER_DSP`` for each new DSP column.

Usage:
    python generate_mac_pblocks.py > mac_pblocks.xdc
"""

from __future__ import annotations

import sys

# ---------------------------------------------------------------------------
# Configuration (edit these before regenerating)
# ---------------------------------------------------------------------------

TOTAL_MACS            = 256       # Number of MAC engines to constrain
DSPS_PER_COLUMN       = 100       # 3-column x 100-row floorplan (256 MACs)
START_DSP_X           = 2         # Starting DSP column (X)
START_DSP_Y           = 0         # Starting DSP row    (Y)
SLICE_START_X_OFFSET  = 30        # SLICE X adjacent to DSP48_X2 on xc7a200t

# Physical box geometry per MAC PBLOCK
DSP_TO_SLICE_Y_RATIO  = 2.5       # CLB rows per DSP row on Artix-7 (heuristic)
SLICE_WIDTH           = 4         # SLICE columns per MAC (runway to the DSP)
SLICE_HEIGHT          = 5         # SLICE rows per MAC (CARRY4 chain + flops)

# RTL hierarchy hooks
HIERARCHY_BASE        = "u_1m_tap_fir"
GEN_LOOP_NAME         = "gen_poly_mac"
INST_NAME             = "u_mac"


# ---------------------------------------------------------------------------
# XDC emission
# ---------------------------------------------------------------------------

XDC_TEMPLATE = (
    "# MAC Engine {i}\n"
    "create_pblock pblock_mac_{i}\n"
    "add_cells_to_pblock [get_pblocks pblock_mac_{i}] "
    "[get_cells -hierarchical -filter "
    "{{NAME =~ *{base}/{loop}\\[{i}\\]\\.{inst}*}}]\n"
    "resize_pblock [get_pblocks pblock_mac_{i}] "
    "-add {{DSP48_X{dx}Y{dy}:DSP48_X{dx}Y{dy}}}\n"
    "resize_pblock [get_pblocks pblock_mac_{i}] "
    "-add {{SLICE_X{sxmin}Y{symin}:SLICE_X{sxmax}Y{symax}}}\n"
)


def emit_header() -> str:
    return (
        "# ---------------------------------------------------------------\n"
        "# Auto-generated by generate_mac_pblocks.py - DO NOT EDIT BY HAND\n"
        f"# Hierarchy base      : {HIERARCHY_BASE}\n"
        f"# Generate loop label : {GEN_LOOP_NAME}\n"
        f"# MAC instance name   : {INST_NAME}\n"
        f"# MAC count           : {TOTAL_MACS}\n"
        f"# DSPs per column     : {DSPS_PER_COLUMN}\n"
        f"# Start DSP (X,Y)     : ({START_DSP_X},{START_DSP_Y})\n"
        f"# SLICE width  / MAC  : {SLICE_WIDTH}\n"
        f"# SLICE height / MAC  : {SLICE_HEIGHT}\n"
        f"# DSP->SLICE Y ratio  : {DSP_TO_SLICE_Y_RATIO}\n"
        f"# SLICE start X off.  : {SLICE_START_X_OFFSET}\n"
        "# Part                : xc7a200tfbg484-3\n"
        "#\n"
        "# NOTE 1: SLICE Y is computed from DSP_TO_SLICE_Y_RATIO * dsp_row.\n"
        "#         The 2.5 default is a heuristic for the xc7a200t; verify\n"
        "#         in the Vivado Device view before committing.\n"
        "# NOTE 2: Generate-loop brackets in the NAME filter are escaped\n"
        "#         as \\[i\\]\\. for Tcl string-match safety.\n"
        "# NOTE 3: SLICE box is now SLICE_WIDTH x SLICE_HEIGHT (4 x 5) to\n"
        "#         host the CARRY4 chain and the dont_touch boundary flops\n"
        "#         introduced in polyphase_mac_engine.sv.\n"
        "# ---------------------------------------------------------------\n"
        "\n"
    )


def emit_block(i: int) -> str:
    col_offset    = i // DSPS_PER_COLUMN
    row_offset    = i %  DSPS_PER_COLUMN

    target_dsp_x  = START_DSP_X + col_offset
    target_dsp_y  = START_DSP_Y + row_offset

    # SLICE X bounding box: shift right by one DSP column's worth of SLICE_WIDTH
    slice_x_min   = SLICE_START_X_OFFSET + (col_offset * SLICE_WIDTH)
    slice_x_max   = slice_x_min + SLICE_WIDTH - 1

    # SLICE Y bounding box: scale DSP row by the CLB/DSP ratio, drop one row
    # so the CARRY4 chain has slack at the DSP boundary, then extend up by
    # SLICE_HEIGHT rows.
    slice_y_base  = int(target_dsp_y * DSP_TO_SLICE_Y_RATIO)
    slice_y_min   = max(0, slice_y_base - 1)
    # Clamp to clock-region ceiling (Y=249) so the +SLICE_HEIGHT spillover at
    # the top of a full DSP column does not extend past the physical SLICE
    # array. The 2.5 DSP-to-SLICE Y ratio is a hard 7-series constant; the
    # last MAC in each filled column gets a slightly shorter PBLOCK instead.
    slice_y_max   = min(slice_y_min + SLICE_HEIGHT - 1, 249)

    return XDC_TEMPLATE.format(
        i=i,
        base=HIERARCHY_BASE,
        loop=GEN_LOOP_NAME,
        inst=INST_NAME,
        dx=target_dsp_x,
        dy=target_dsp_y,
        sxmin=slice_x_min,
        sxmax=slice_x_max,
        symin=slice_y_min,
        symax=slice_y_max,
    )


def main(argv: list[str]) -> int:
    out = sys.stdout
    out.write(emit_header())
    for i in range(TOTAL_MACS):
        out.write(emit_block(i))
        out.write("\n")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
